### ISSUE TITLE
Use latest and greatest NuKeeper automatically

### ISSUE THREAD

**Issue by MarcBruins** [NuKeeperDotNet/NuKeeper-AzureDevops-extension#11]
There are some issues that require the extension to use attached binary. We cannot use `dotnet tool install` in our task because this requires a reboot of the shell(which will not happen in azure devops)

Another option that i've tried which is already a bit cumbersome is to use the dockerimage. This is technically possible but not a really clean solution because it requires a docker image download. 

What we currently do is to attach the binary in the extension and reference that from typescript. Any suggestions on how to move forward are more then welcome.

**Comment by OneCyrus** [comment]
i guess the approach which most extensions use is to have a tool installer. e.g. create an additional task like "Nukeeper Installer" which installs the defined version. have a look at the "Nuget Tool Installer" or the ".Net Core SDK Installer".

**Comment by MarcBruins** [comment]
Thanks for the response @OneCyrus. This still doesn't help as a dotnet tool command needs a restart of the CLI, that doesn't happen in your pipeline.

I've fixed it by downloading the latest package from nuget and use that in #18 I'm very happy that i can close this! 🎉

**Comment by OneCyrus** [comment]
yes, but the global tool is not needed for this as you found out in your new solution. but i would do a native javascript version like e.g. the yarn installer as the new version has new problems (I'll open another issue): https://github.com/geeklearningio/gl-vsts-tasks-yarn/blob/master/Tasks/YarnInstaller/yarnToolInstallerTask.ts
