### ISSUE TITLE
Support Azure DevOps Nuget Feeds

### ISSUE THREAD

**Issue by dpiessens** [NuKeeperDotNet/NuKeeper-AzureDevops-extension#15]
NuKeeper is a bit more difficult to work with if you host you own NuGet package feeds. It would be great if you could specify if you want to use those feeds like in the NuGet restore task and have it generate and pass in a custom file to help with that process.

Example code for how the NuGet task creates the file is here: https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/NuGetRestoreV1/nugetinstaller.ts

Let me know if you're interested in this task and I'll create a branch and PR for it.

**Comment by MarcBruins** [comment]
Why is it difficult to work with your own NuGet feeds? What problem do you run into? This would be a nice feature but i'm having no problems with this at the moment(but my setup might be different)

**Comment by dpiessens** [comment]
The problem is authentication. Yes we have a nuget.config file in our Repo but it's only effective on our workstations because of the built-in windows credential cache. On Azure DevOps we have use the feed because it generates a token to access the repository. Without it, all restore calls come back with a failure.
We can use a static token in the config, but that breaks a lot of security best practices. The feature I'm proposing would create the temporary file the same way the .net build and nuget restore tasks do, pass that into NuKeeper and then remove the file once complete.

**Comment by MarcBruins** [comment]
You are right, we use a different approach that uses a replace tokens in the nuget.config but i can imagine other teams having different approaches.

The solution sounds like a good idea, are you able to work on that and submit a PR? I don't think you can test that locally but the example should get you pretty far

**Comment by MarcBruins** [comment]
It seems like a lot of work actually. Can't you just add that task and do a nuget restore? That should create a temp file Nuget.Config file at the root with the credentials inside it.

**Comment by dpiessens** [comment]
The step creates the nuget.config file in a working directory, specifies it
during the step as an override and then deletes it once the step is
complete, which unfounately prevents the operation. I'm tinkering with a
workaround, but it would have to be in the docs as it isn't a fix all.

**Comment by MarcBruins** [comment]
I agree that it is a workaround and we should keep this issue open, any help with this would be appreciated

**Comment by MarcBruins** [comment]
Go ahead :)

**Comment by MarcBruins** [comment]
@dpiessens added basic implementation that should work for dev.azure.com. Can you test it and let me know if it works for you?

**Comment by MarcBruins** [comment]
Should work for azure devops now. Please let me know in another issue if there are still any issues

**Comment by MaxMommersteeg** [comment]
Should also work when running Azure DevOps from the old url `organisation.visualstudio.com/`

**Comment by kipusoep** [comment]
So how does this work? In my case it doesn't seem to connect to the nuget feed automatically.
