### ISSUE TITLE
curl is not a preinstalled tool on most build servers

### ISSUE THREAD

**Issue by OneCyrus** [NuKeeperDotNet/NuKeeper-AzureDevops-extension#19]
with the new version we get the following error:

```
Error: Unable to locate executable file: 'curl'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
```

as curl is not a default tool on a Windows Server 2016 installation. I would handle the file download in JS

**Comment by MarcBruins** [comment]
Right most agent should have curl but I agree that a js file download would be easier. Probably some npm package out there that makes it simple. Can you make a PR?

**Comment by OneCyrus** [comment]
PR is here #20
