### ISSUE TITLE
change nukeeper download to azure pipelines tool lib

### ISSUE THREAD

**Issue by OneCyrus** [NuKeeperDotNet/NuKeeper-AzureDevops-extension#22]
the extraction is still not very reliable as there are some overwrite issues. for a proper solution the download and extraction should be done with the azure pipelines tool library.

see: https://github.com/Microsoft/azure-pipelines-tool-lib
https://github.com/Microsoft/azure-pipelines-tool-lib/blob/master/sample.ts

**Comment by OneCyrus** [comment]
version list of nukeeper is found through this API:
https://api.nuget.org/v3/registration3/nukeeper/index.json 
or just the version numbers here: https://api.nuget.org/v3-flatcontainer/nukeeper/index.json

and then we could use the v3 api for download
```https://api.nuget.org/v3-flatcontainer/nukeeper/{version}/nukeeper.{version}.nupkg```
https://api.nuget.org/v3-flatcontainer/nukeeper/0.17.0/nukeeper.0.17.0.nupkg

**Comment by MarcBruins** [comment]
That azure pipelines tool library looks promising but what are the overwrite issues that we are facing?

**Comment by MarcBruins** [comment]
Can you join gitter? That makes it's easy to communicate: https://gitter.im/NuKeeperDotNet/Lobby

**Comment by MarcBruins** [comment]
Think we can close this for now. We use the new library. The nuget v3 should be a separate issue with a lower priority than this.

**Comment by OneCyrus** [comment]
the issue with the current implementation is that it won‘t download newer nukeeper versions as it is cached forever. the cache won‘t be resetted until a new extension version is released or the task is removed/server resetted.

**Comment by MarcBruins** [comment]
This is fixed now thanks to @jessehouwing his help. We implemented a tool installer that allows you to select a specific version and cache it. It has some pretty nifty features: https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension/blob/master/nukeeper/task.json#L42
