### ISSUE TITLE
Fails to perform git pull

### ISSUE THREAD

**Issue by SirFlau** [NuKeeperDotNet/NuKeeper-AzureDevops-extension#28]
I am relatively new to development in general, so I am properly overlooking something simple. When I queue up my pipeline it just get stuck on a git pull command, and I have to cancel or wait an hour for the timeout.
If you need any additional info let me know.

I hope you can help, and thanks in advance.

##[section]Starting: NuKeeper
==============================================================================
Task         : NuKeeper
Description  : Version 0.2.4
Version      : 0.2.4
Author       : NuKeeper
Help         : For help please visit https://github.com/NuKeeperDotNet/NuKeeper
==============================================================================
Downloading: https://www.nuget.org/api/v2/package/NuKeeper
(node:2960) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2960) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2960) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2960) Warning: Use Cipheriv for counter mode of aes-256-ctr
Extracting archive
[command]C:\Windows\system32\chcp.com 65001
Active code page: 65001
[command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\nukeeper.nupkg', 'D:\a\_temp\nukeeper')"
[command]C:\agents\2.148.0\externals\git\cmd\git.exe checkout dev
Switched to a new branch 'dev'
Branch 'dev' set up to track remote branch 'dev' from 'origin'.
[command]C:\agents\2.148.0\externals\git\cmd\git.exe pull
##[error]The operation was canceled.
##[section]Finishing: NuKeeper

**Comment by MarcBruins** [comment]
Thanks for reporting, I'm seeing the same behaviour. This is a bug and i'm not sure why. Would love any help here.

**Comment by MarcBruins** [comment]
There is a missing checkmark that you need to add. Added it in the readme with a screenshot!
