### ISSUE TITLE
set git config just for the local repo and not global

### ISSUE THREAD

**Issue by OneCyrus** [NuKeeperDotNet/NuKeeper-AzureDevops-extension#30]
we should remove --global from the config command. so that we don't overwrite global user settings.

https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension/blob/5ee9eb6df64531cc5940171512460604740528c4/nukeeper/src/NuKeeper.ts#L26-L27

**Comment by MarcBruins** [comment]
Indeed, i'll fix that now

**Comment by MarcBruins** [comment]
Fixed in `0.4.3`
