### ISSUE TITLE
Git fetch could not read username error

### ISSUE THREAD

**Issue by Mobrockers** [NuKeeperDotNet/NuKeeper-AzureDevops-extension#32]
Using the azure devops extension I get the following error:

Starting: NuKeeper
==============================================================================
Task         : NuKeeper
Description  : Version 0.4.5
Version      : 0.4.5
Author       : NuKeeper
Help         : For help please visit https://github.com/NuKeeperDotNet/NuKeeper
==============================================================================
\9\externals\git\cmd\git.exe fetch
fatal: could not read Username for 'https://company.visualstudio.com': terminal prompts disabled
##[error]Error: The process 'D:\9\externals\git\cmd\git.exe' failed with exit code 128
Finishing: NuKeeper

I'm also noticing that the extension version number is higher than the highest version number in this repo for some reason.

**Comment by MarcBruins** [comment]
Did it ever work for you or is it the first time it is breaking?

**Comment by Mobrockers** [comment]
It's my first time using nukeeper and I keep getting this error message

**Comment by MarcBruins** [comment]
Should be fixed by now. Somehow the `git fetch` command wants a password now where it didn't want that before.
