### ISSUE TITLE
[error]Unhandled: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by Mobrockers** [NuKeeperDotNet/NuKeeper-AzureDevops-extension#39]
```
Starting: NuKeeper
==============================================================================
Task         : NuKeeper
Description  : Version 0.4.34
Version      : 0.4.34
Author       : NuKeeper
Help         : For help please visit https://github.com/NuKeeperDotNet/NuKeeper
==============================================================================
##[error]Unhandled: Path must be a string. Received undefined
Finishing: NuKeeper
```
Here are my settings, is any of this incorrect?:

![image](https://user-images.githubusercontent.com/3595932/59769879-48cb7d80-92a7-11e9-8d71-f31bea1692ab.png)

**Comment by MaxMommersteeg** [comment]
Hi,

You shouldn't have to set the nukeeper command expliticly (`repo`) since it is always running `nukeeper repo` from the Azure DevOps extension: https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension/blob/master/nukeeper/src/NuKeeper.ts#L48

Not sure why you're passing in the azure devops token though. The `Arguments` field is only for NuKeeper's own commands: https://nukeeper.com/basics/configuration/

An example of valid arguments would be:
`--verbosity detailed --change Major --include FakeItEasy --consolidate`

**Comment by Mobrockers** [comment]
I don't remember there being any documentation on the plugin usage when I first tried out the extension months ago. Since it didn't work I kinda forgot about it. I now see configuration documentation has been made, so I'll try setting it up using those docs.

**Comment by Mobrockers** [comment]
I am still getting the error, it seems unrelated to my config, it seems to be an error with the task metadata?

```
##[debug]Evaluating condition for step: 'NuKeeper' |  
-- | --
  | ##[debug]Evaluating: succeeded() |  
  | ##[debug]Evaluating succeeded: |  
  | ##[debug]=> True |  
  | ##[debug]Result: True |  
  | Starting: NuKeeper |  
  | ============================================================================== |  
  | Task         : NuKeeper |  
  | Description  : Version 0.4.34 |  
  | Version      : 0.4.34 |  
  | Author       : NuKeeper |  
  | Help         : For help please visit https://github.com/NuKeeperDotNet/NuKeeper |  
  | ============================================================================== |  
  | ##[debug]agent.TempDirectory=D:\9\_work\_temp |  
  | ##[debug]loading inputs and endpoints |  
  | ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN |  
  | ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION |  
  | ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION |  
  | ##[debug]loading INPUT_ARGUMENTS |  
  | ##[debug]loading INPUT_CHECKLATEST |  
  | ##[debug]loading INPUT_TARGETFOLDER |  
  | ##[debug]loading INPUT_VERSION |  
  | ##[debug]loading SECRET_NUKEEPER_AZURE_DEVOPS_TOKEN |  
  | ##[debug]loaded 8 |  
  | ##[debug]Agent.ProxyUrl=undefined |  
  | ##[debug]Agent.CAInfo=undefined |  
  | ##[debug]Agent.ClientCert=undefined |  
  | ##[debug]Agent.SkipCertValidation=undefined |  
  | ##[debug]Agent.ProxyUrl=undefined |  
  | ##[debug]Agent.CAInfo=undefined |  
  | ##[debug]Agent.ClientCert=undefined |  
  | ##[debug]check path : D:\9\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.4.34\node_modules\azure-pipelines-tool-lib\lib.json |  
  | ##[debug]adding resource file: D:\9\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.4.34\node_modules\azure-pipelines-tool-lib\lib.json |  
  | ##[debug]system.culture=en-US |  
  | ##[debug]Pipeline.Workspace=undefined |  
  | ##[debug]task result: Failed |  
  | ##[error]Unhandled: Path must be a string. Received undefined |  
  | ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Path must be a string. Received undefined |  
  | ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Path must be a string. Received undefined |  
  | Finishing: NuKeeper
```

Settings:

![image](https://user-images.githubusercontent.com/3595932/60510445-b2984e00-9ccf-11e9-98d3-385262c61d18.png)

**Comment by MaxMommersteeg** [comment]
@MarcBruins Could you take a look?

**Comment by Mobrockers** [comment]
https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension/blob/d7534f13dcb19e7ff41e5905422cf1649a3d2ec3/nukeeper/src/FeedInstaller.ts#L16

According to my debug logging this variable is undefined (`| ##[debug]Pipeline.Workspace=undefined |`)and used in a path.join, this might cause this error.

**Comment by Mobrockers** [comment]
I suggest replacing Pipeline.Workspace with Agent.BuildDirectory because apparently Pipeline.Workspace is not always defined in a pipeline.

I used this powershell script to see the values during the pipeline run:
```
Write-Host "Agent.BuildDirectory: $(Agent.BuildDirectory)"
Write-Host "Pipeline.Workspace: $(Pipeline.Workspace)"
```

This was the result:

```
Agent.BuildDirectory: D:\9\_work\167

Pipeline.Workspace : The term 'Pipeline.Workspace' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is
correct and try again.
```

**Comment by MarcBruins** [comment]
Did you test locally? Then it make sense that there is no `Pipeline.Workspace`. The temp `Nuget.Config` should be on the same level or in a subdirectory of the source that you are running nukeeper on.

**Comment by Mobrockers** [comment]
If you look at the docs for pipeline.workspace then you'll see the example value is the same as agent.buildDirectory. Since in my build pipeline pipeline.workspace is undefined I cannot test what this variable is actually filled with in a build, I can only take the example value on that page as truth. I'm not even trying to attach a private feed, I am simply making an assumption to the error I am getting as I noticed that pipeline.workspace is undefined in my build and the error I get is that the path is undefined (which is the error I would expect when path.join is called with undefined). In any case, pipeline.workspace seems to be the same value as agent.buildDirectory according to the documentation so to me it seems safe to check the variable exists and if not to replace it with agent.buildDirectory (but only if it doesn't exist).

**Comment by MaxMommersteeg** [comment]
Links to docs for reference:
- [Pipeline.Workspace](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#pipeline-variables)
- [Agent.BuildDirectory](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables)

**Comment by Mobrockers** [comment]
createFeed is always called so the const is always resolved to a valid path so the 'Pipeline.Workspace' variable is always requested and in the case it does not exist it errors and causes a failure on the task run.

https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension/blob/3859bfdd525d8c1bd2b85d154f320bc3df63aa00/nukeeper/src/NuKeeper.ts#L14

The variables are exactly the same, they are the build definition root directory (eg c:\agent\_work\1)
https://github.com/microsoft/azure-pipelines-agent/blob/22cef4ab545acc10123de03c5384671d4ac13123/src/Agent.Worker/Build/BuildJobExtension.cs#L191
https://github.com/microsoft/azure-pipelines-agent/blob/22cef4ab545acc10123de03c5384671d4ac13123/src/Agent.Worker/Build/BuildJobExtension.cs#L200

The pipeline.workspace variable seems relatively new so perhaps not all consumers have had this agent version pushed yet. I am using on-premise agents, they should not update until a plugin requires it. See:
https://github.com/microsoft/azure-pipelines-agent/commit/22cef4ab545acc10123de03c5384671d4ac13123

So you can either merge my PR and be compatible with more azure devops agent versions or you can add a minimum agent version demand in the task.json with value 2.154.0 (the version where the variable was introduced). IIRC settings this demand in the task.json forces azure devops agents to self-update before running a build (assuming they have an internet connection).
