### ISSUE TITLE
Nukeeper not working when using multi repo pipelines

### ISSUE THREAD

**Issue by Rora** [NuKeeperDotNet/NuKeeper-AzureDevops-extension#54]
Our team tries to create a pipeline which will be able to run nukeeper for every repository. To do this we've added a checkout step which uses a variable like so:

- checkout: git://platform/$(repo-name)@$(branch-name)
The checkout works fine, however using NuKeeper (which uses the build variable Build.SourceBranch) won't work since the 'Build.SourceBranch' variable isn't updated by the checkout, resulting in a failing nukeeper.

A fix would be to a 'target-branch' option to the build task. This option might provide usefull in other use cases as well.

P.S. IMO there should be a up to date build variable that nukeeper would be able to use, however this is not the case at the moment. I've added an issue for this as well https://developercommunity.visualstudio.com/content/problem/1052569/multi-repo-checkout-not-updating-build-variables.html

**Comment by Rora** [comment]
Added PR https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension/pull/55 for if you agree with the opted solution

**Comment by MarcBruins** [comment]
Updated the PR and there is a new release. Can you confirm that it works? The only thing you have to do is add the `--targetBranch origin/mybranch` to the `Arguments` field
